const collection = [
  {
    collectionname: "AR Rahman Collection 1",
    ArtistName: "AR Rahman",
    type: "Album",
    duration: "00:83:05",
    size: "113MB",
    count: 20,
    id: 3785,
    release: "26 May 2024, 11:35 am",
  },
  {
    collectionname: "Alan Silvestri Collection 2",
    ArtistName: "Alan Silvestri",
    type: "Album",
    duration: "00:35:29",
    size: "81MB",
    count: 11,
    id: 4440,
    release: "09 Jun 2024, 18:50 pm",
  },
  {
    collectionname: "AR Rahman Collection 3",
    ArtistName: "AR Rahman",
    type: "Single",
    duration: "00:03:02",
    size: "5MB",
    count: 1,
    id: 7267,
    release: "03 Feb 2025, 04:36 am",
  },
  {
    collectionname: "James Horner Collection 4",
    ArtistName: "James Horner",
    type: "Single",
    duration: "00:04:40",
    size: "6MB",
    count: 1,
    id: 6625,
    release: "19 Dec 2024, 21:30 pm",
  },
  {
    collectionname: "Alan Silvestri Collection 5",
    ArtistName: "Alan Silvestri",
    type: "Single",
    duration: "00:05:48",
    size: "8MB",
    count: 1,
    id: 1556,
    release: "22 Apr 2025, 08:11 am",
  },
  {
    collectionname: "Illayaraja Collection 6",
    ArtistName: "Illayaraja",
    type: "Album",
    duration: "00:35:08",
    size: "40MB",
    count: 8,
    id: 9686,
    release: "08 May 2024, 06:41 am",
  },
  {
    collectionname: "Illayaraja Collection 7",
    ArtistName: "Illayaraja",
    type: "Album",
    duration: "00:44:54",
    size: "100MB",
    count: 11,
    id: 9181,
    release: "07 Jan 2025, 11:31 am",
  },
  {
    collectionname: "Yanni Collection 8",
    ArtistName: "Yanni",
    type: "Single",
    duration: "00:05:05",
    size: "9MB",
    count: 1,
    id: 5661,
    release: "09 Sep 2024, 11:03 am",
  },
  {
    collectionname: "Alan Silvestri Collection 9",
    ArtistName: "Alan Silvestri",
    type: "Album",
    duration: "00:64:14",
    size: "134MB",
    count: 16,
    id: 5984,
    release: "15 Feb 2024, 03:17 am",
  },
  {
    collectionname: "Alan Silvestri Collection 10",
    ArtistName: "Alan Silvestri",
    type: "Album",
    duration: "00:64:00",
    size: "122MB",
    count: 14,
    id: 5627,
    release: "05 Sep 2024, 09:47 am",
  },
  {
    collectionname: "Ennio Morricone Collection 11",
    ArtistName: "Ennio Morricone",
    type: "EP",
    duration: "00:58:05",
    size: "145MB",
    count: 16,
    id: 2712,
    release: "26 Jul 2024, 16:55 pm",
  },
  {
    collectionname: "Two Steps From Hell Collection 12",
    ArtistName: "Two Steps From Hell",
    type: "Album",
    duration: "00:56:50",
    size: "151MB",
    count: 18,
    id: 3562,
    release: "10 Feb 2024, 23:14 pm",
  },
  {
    collectionname: "AR Rahman Collection 13",
    ArtistName: "AR Rahman",
    type: "EP",
    duration: "00:63:39",
    size: "127MB",
    count: 14,
    id: 1149,
    release: "03 Jan 2025, 02:43 am",
  },
  {
    collectionname: "Jorge Rivera-Herrans Collection 14",
    ArtistName: "Jorge Rivera-Herrans",
    type: "Single",
    duration: "00:05:20",
    size: "6MB",
    count: 1,
    id: 9389,
    release: "03 Jan 2024, 05:12 am",
  },
  {
    collectionname: "Yanni Collection 15",
    ArtistName: "Yanni",
    type: "Single",
    duration: "00:03:26",
    size: "6MB",
    count: 1,
    id: 7994,
    release: "08 Jun 2025, 08:29 am",
  },
  {
    collectionname: "Two Steps From Hell Collection 16",
    ArtistName: "Two Steps From Hell",
    type: "EP",
    duration: "00:59:36",
    size: "87MB",
    count: 17,
    id: 7640,
    release: "22 Jan 2024, 09:01 am",
  },
  {
    collectionname: "Ludovico Einaudi Collection 17",
    ArtistName: "Ludovico Einaudi",
    type: "EP",
    duration: "00:38:12",
    size: "70MB",
    count: 10,
    id: 6763,
    release: "05 Jun 2025, 02:39 am",
  },
  {
    collectionname: "Howard Shore Collection 18",
    ArtistName: "Howard Shore",
    type: "Album",
    duration: "00:65:17",
    size: "101MB",
    count: 18,
    id: 7195,
    release: "28 Dec 2025, 06:17 am",
  },
  {
    collectionname: "James Horner Collection 19",
    ArtistName: "James Horner",
    type: "Album",
    duration: "00:36:20",
    size: "109MB",
    count: 12,
    id: 6437,
    release: "18 Jun 2024, 23:21 pm",
  },
  {
    collectionname: "Jorge Rivera-Herrans Collection 20",
    ArtistName: "Jorge Rivera-Herrans",
    type: "Album",
    duration: "00:55:22",
    size: "138MB",
    count: 16,
    id: 9741,
    release: "04 Jan 2025, 19:35 pm",
  },
  {
    collectionname: "Max Richter Collection 21",
    ArtistName: "Max Richter",
    type: "EP",
    duration: "00:61:04",
    size: "104MB",
    count: 15,
    id: 7516,
    release: "25 Feb 2025, 19:52 pm",
  },
  {
    collectionname: "Philip Glass Collection 22",
    ArtistName: "Philip Glass",
    type: "EP",
    duration: "00:54:07",
    size: "90MB",
    count: 12,
    id: 9958,
    release: "09 Sep 2024, 07:36 am",
  },
  {
    collectionname: "Jorge Rivera-Herrans Collection 23",
    ArtistName: "Jorge Rivera-Herrans",
    type: "EP",
    duration: "00:29:11",
    size: "52MB",
    count: 6,
    id: 8079,
    release: "27 Nov 2025, 20:24 pm",
  },
  {
    collectionname: "Hans Zimmer Collection 24",
    ArtistName: "Hans Zimmer",
    type: "EP",
    duration: "00:74:50",
    size: "153MB",
    count: 18,
    id: 9763,
    release: "05 Jul 2024, 18:44 pm",
  },
  {
    collectionname: "Jorge Rivera-Herrans Collection 25",
    ArtistName: "Jorge Rivera-Herrans",
    type: "Single",
    duration: "00:03:34",
    size: "10MB",
    count: 1,
    id: 4806,
    release: "10 Mar 2025, 20:36 pm",
  },
  {
    collectionname: "James Horner Collection 26",
    ArtistName: "James Horner",
    type: "Single",
    duration: "00:04:45",
    size: "8MB",
    count: 1,
    id: 8903,
    release: "02 May 2024, 10:19 am",
  },
  {
    collectionname: "AR Rahman Collection 27",
    ArtistName: "AR Rahman",
    type: "Single",
    duration: "00:04:13",
    size: "6MB",
    count: 1,
    id: 9109,
    release: "11 Apr 2024, 14:31 pm",
  },
  {
    collectionname: "James Horner Collection 28",
    ArtistName: "James Horner",
    type: "Single",
    duration: "00:03:09",
    size: "10MB",
    count: 1,
    id: 5402,
    release: "27 Sep 2025, 13:09 pm",
  },
  {
    collectionname: "Howard Shore Collection 29",
    ArtistName: "Howard Shore",
    type: "Album",
    duration: "00:31:01",
    size: "77MB",
    count: 8,
    id: 3656,
    release: "05 Jul 2024, 21:03 pm",
  },
  {
    collectionname: "John Williams Collection 30",
    ArtistName: "John Williams",
    type: "EP",
    duration: "00:73:25",
    size: "140MB",
    count: 16,
    id: 8542,
    release: "02 Feb 2024, 05:58 am",
  },
  {
    collectionname: "Two Steps From Hell Collection 31",
    ArtistName: "Two Steps From Hell",
    type: "EP",
    duration: "00:15:03",
    size: "39MB",
    count: 5,
    id: 5021,
    release: "02 Apr 2024, 23:48 pm",
  },
  {
    collectionname: "James Horner Collection 32",
    ArtistName: "James Horner",
    type: "EP",
    duration: "00:38:46",
    size: "56MB",
    count: 11,
    id: 9200,
    release: "25 Feb 2025, 07:22 am",
  },
  {
    collectionname: "Ennio Morricone Collection 33",
    ArtistName: "Ennio Morricone",
    type: "Album",
    duration: "00:73:07",
    size: "121MB",
    count: 16,
    id: 3674,
    release: "26 Oct 2025, 06:04 am",
  },
  {
    collectionname: "Yanni Collection 34",
    ArtistName: "Yanni",
    type: "Single",
    duration: "00:05:50",
    size: "8MB",
    count: 1,
    id: 8403,
    release: "12 Jan 2024, 23:55 pm",
  },
  {
    collectionname: "Ennio Morricone Collection 35",
    ArtistName: "Ennio Morricone",
    type: "Album",
    duration: "00:44:39",
    size: "138MB",
    count: 14,
    id: 8196,
    release: "18 Mar 2024, 12:02 pm",
  },
  {
    collectionname: "Philip Glass Collection 36",
    ArtistName: "Philip Glass",
    type: "Album",
    duration: "00:32:18",
    size: "56MB",
    count: 9,
    id: 1419,
    release: "16 May 2025, 15:35 pm",
  },
  {
    collectionname: "John Williams Collection 37",
    ArtistName: "John Williams",
    type: "EP",
    duration: "00:22:53",
    size: "34MB",
    count: 6,
    id: 7282,
    release: "22 Jun 2025, 02:51 am",
  },
  {
    collectionname: "James Horner Collection 38",
    ArtistName: "James Horner",
    type: "EP",
    duration: "00:41:14",
    size: "75MB",
    count: 9,
    id: 7050,
    release: "21 Mar 2024, 17:11 pm",
  },
  {
    collectionname: "Yanni Collection 39",
    ArtistName: "Yanni",
    type: "EP",
    duration: "00:42:29",
    size: "85MB",
    count: 13,
    id: 5655,
    release: "02 May 2025, 15:46 pm",
  },
  {
    collectionname: "Illayaraja Collection 40",
    ArtistName: "Illayaraja",
    type: "Single",
    duration: "00:05:43",
    size: "7MB",
    count: 1,
    id: 5111,
    release: "10 Dec 2025, 18:53 pm",
  },
  {
    collectionname: "AR Rahman Collection 41",
    ArtistName: "AR Rahman",
    type: "Single",
    duration: "00:04:01",
    size: "8MB",
    count: 1,
    id: 5597,
    release: "28 May 2025, 03:15 am",
  },
  {
    collectionname: "Danny Elfman Collection 42",
    ArtistName: "Danny Elfman",
    type: "EP",
    duration: "00:19:38",
    size: "40MB",
    count: 5,
    id: 2841,
    release: "01 May 2024, 06:20 am",
  },
  {
    collectionname: "Alan Silvestri Collection 43",
    ArtistName: "Alan Silvestri",
    type: "Single",
    duration: "00:04:41",
    size: "5MB",
    count: 1,
    id: 3220,
    release: "11 Jun 2024, 19:59 pm",
  },
  {
    collectionname: "Ennio Morricone Collection 44",
    ArtistName: "Ennio Morricone",
    type: "EP",
    duration: "00:31:20",
    size: "47MB",
    count: 7,
    id: 5145,
    release: "14 Apr 2025, 18:20 pm",
  },
  {
    collectionname: "Ennio Morricone Collection 45",
    ArtistName: "Ennio Morricone",
    type: "EP",
    duration: "00:45:43",
    size: "56MB",
    count: 11,
    id: 7994,
    release: "20 Feb 2024, 10:00 am",
  },
  {
    collectionname: "Howard Shore Collection 46",
    ArtistName: "Howard Shore",
    type: "EP",
    duration: "00:59:25",
    size: "166MB",
    count: 17,
    id: 5347,
    release: "09 Oct 2025, 11:45 am",
  },
  {
    collectionname: "Alan Silvestri Collection 47",
    ArtistName: "Alan Silvestri",
    type: "Single",
    duration: "00:04:51",
    size: "8MB",
    count: 1,
    id: 1661,
    release: "12 May 2025, 01:06 am",
  },
  {
    collectionname: "Philip Glass Collection 48",
    ArtistName: "Philip Glass",
    type: "Album",
    duration: "00:95:49",
    size: "193MB",
    count: 20,
    id: 1897,
    release: "12 Jan 2025, 15:46 pm",
  },
  {
    collectionname: "Howard Shore Collection 49",
    ArtistName: "Howard Shore",
    type: "Single",
    duration: "00:04:41",
    size: "5MB",
    count: 1,
    id: 5947,
    release: "05 Jul 2024, 11:26 am",
  },
  {
    collectionname: "Max Richter Collection 50",
    ArtistName: "Max Richter",
    type: "Album",
    duration: "00:51:09",
    size: "88MB",
    count: 15,
    id: 9913,
    release: "27 Jan 2024, 11:34 am",
  },
];
const CollectionswithSongs = [
  {
    id: 3785,
    songs: [
      {
        song: "Storm of Destiny",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:45",
        size: "6MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Illayaraja & The Symphony",
        duration: "00:03:43",
        size: "3MB",
      },
      {
        song: "Odysseus' Journey",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:05:11",
        size: "9MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Alan Silvestri Band",
        duration: "00:02:51",
        size: "3MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Illayaraja & The Symphony",
        duration: "00:04:00",
        size: "6MB",
      },
      {
        song: "The Last Stand",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:02:50",
        size: "8MB",
      },
      {
        song: "Helen's Lament",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:06:28",
        size: "5MB",
      },
      {
        song: "Epic Overture",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:40",
        size: "9MB",
      },
      {
        song: "The Siege",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:20",
        size: "9MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Alan Silvestri Band",
        duration: "00:05:03",
        size: "7MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:03:06",
        size: "5MB",
      },
      {
        song: "Trojan War",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:05:02",
        size: "8MB",
      },
      {
        song: "The Final Battle",
        Performers: "James Horner & The Epic Choir",
        duration: "00:04:35",
        size: "9MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Yanni & The Fusion Band",
        duration: "00:03:23",
        size: "8MB",
      },
      {
        song: "A New Dawn",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:22",
        size: "9MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:15",
        size: "9MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Illayaraja & The Symphony",
        duration: "00:05:40",
        size: "7MB",
      },
      {
        song: "Helen's Lament",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:20",
        size: "10MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "James Horner & The Epic Choir",
        duration: "00:03:57",
        size: "4MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:06:50",
        size: "6MB",
      },
    ],
  },
  {
    id: 4440,
    songs: [
      {
        song: "Odysseus' Journey",
        Performers: "Max Richter Piano Quartet",
        duration: "00:04:13",
        size: "10MB",
      },
      {
        song: "Valhalla Awaits",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:03:00",
        size: "7MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "John Williams Philharmonic",
        duration: "00:05:33",
        size: "7MB",
      },
      {
        song: "The Final Battle",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:21",
        size: "9MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "James Horner & The Epic Choir",
        duration: "00:05:00",
        size: "9MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Yanni & The Fusion Band",
        duration: "00:04:58",
        size: "9MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Yanni & The Fusion Band",
        duration: "00:03:57",
        size: "10MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "John Williams Philharmonic",
        duration: "00:05:08",
        size: "5MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Alan Silvestri Band",
        duration: "00:04:21",
        size: "7MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "John Williams Philharmonic",
        duration: "00:03:37",
        size: "7MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:50",
        size: "10MB",
      },
    ],
  },
  {
    id: 7267,
    songs: [
      {
        song: "The Forgotten Melody",
        Performers: "Alan Silvestri Band",
        duration: "00:04:41",
        size: "9MB",
      },
    ],
  },
  {
    id: 6625,
    songs: [
      {
        song: "Odysseus' Journey",
        Performers: "Max Richter Piano Quartet",
        duration: "00:04:56",
        size: "5MB",
      },
    ],
  },
  {
    id: 1556,
    songs: [
      {
        song: "The Horse and the Infant",
        Performers: "Illayaraja & The Symphony",
        duration: "00:04:24",
        size: "6MB",
      },
    ],
  },
  {
    id: 9686,
    songs: [
      {
        song: "Odysseus' Journey",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:30",
        size: "7MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:06:27",
        size: "5MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:03",
        size: "9MB",
      },
      {
        song: "A New Dawn",
        Performers: "Illayaraja & The Symphony",
        duration: "00:06:50",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:04:01",
        size: "10MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:05:02",
        size: "5MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:02:07",
        size: "5MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Illayaraja & The Symphony",
        duration: "00:05:40",
        size: "6MB",
      },
    ],
  },
  {
    id: 9181,
    songs: [
      {
        song: "Rise of the Phoenix",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:42",
        size: "7MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:12",
        size: "10MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:15",
        size: "9MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:03:31",
        size: "8MB",
      },
      {
        song: "Epic Overture",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:06:12",
        size: "10MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:24",
        size: "3MB",
      },
      {
        song: "Epic Overture",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:55",
        size: "3MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Max Richter Piano Quartet",
        duration: "00:03:06",
        size: "7MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Yanni & The Fusion Band",
        duration: "00:03:46",
        size: "10MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:06:25",
        size: "6MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Yanni & The Fusion Band",
        duration: "00:06:24",
        size: "6MB",
      },
    ],
  },
  {
    id: 5661,
    songs: [
      {
        song: "The Wooden Horse",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:06:30",
        size: "9MB",
      },
    ],
  },
  {
    id: 5984,
    songs: [
      {
        song: "Legends Never Die",
        Performers: "John Williams Philharmonic",
        duration: "00:04:57",
        size: "10MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "AR Rahman & The Choir",
        duration: "00:04:36",
        size: "10MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Alan Silvestri Band",
        duration: "00:04:53",
        size: "5MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:40",
        size: "10MB",
      },
      {
        song: "Helen's Lament",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:02:33",
        size: "4MB",
      },
      {
        song: "A New Dawn",
        Performers: "James Horner & The Epic Choir",
        duration: "00:05:12",
        size: "7MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:14",
        size: "8MB",
      },
      {
        song: "The Siege",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:20",
        size: "3MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Alan Silvestri Band",
        duration: "00:05:45",
        size: "8MB",
      },
      {
        song: "The Siege",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:29",
        size: "4MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "John Williams Philharmonic",
        duration: "00:05:43",
        size: "3MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:21",
        size: "6MB",
      },
      {
        song: "Helen's Lament",
        Performers: "John Williams Philharmonic",
        duration: "00:06:58",
        size: "3MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:06:48",
        size: "6MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:03",
        size: "4MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:04:37",
        size: "8MB",
      },
    ],
  },
  {
    id: 5627,
    songs: [
      {
        song: "The Forgotten Melody",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:06:12",
        size: "6MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Yanni & The Fusion Band",
        duration: "00:05:57",
        size: "4MB",
      },
      {
        song: "The Final Battle",
        Performers: "Max Richter Piano Quartet",
        duration: "00:03:17",
        size: "5MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Alan Silvestri Band",
        duration: "00:03:48",
        size: "4MB",
      },
      {
        song: "Epic Overture",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:04:25",
        size: "7MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Illayaraja & The Symphony",
        duration: "00:04:56",
        size: "6MB",
      },
      {
        song: "Trojan War",
        Performers: "James Horner & The Epic Choir",
        duration: "00:05:48",
        size: "6MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Alan Silvestri Band",
        duration: "00:06:48",
        size: "6MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Yanni & The Fusion Band",
        duration: "00:03:54",
        size: "10MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "James Horner & The Epic Choir",
        duration: "00:06:54",
        size: "5MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Illayaraja & The Symphony",
        duration: "00:03:01",
        size: "8MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:51",
        size: "7MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:03:19",
        size: "6MB",
      },
      {
        song: "The Siege",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:46",
        size: "4MB",
      },
    ],
  },
  {
    id: 2712,
    songs: [
      {
        song: "The Horse and the Infant",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:03:35",
        size: "6MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:06:56",
        size: "8MB",
      },
      {
        song: "A New Dawn",
        Performers: "James Horner & The Epic Choir",
        duration: "00:05:20",
        size: "7MB",
      },
      {
        song: "Legends Never Die",
        Performers: "James Horner & The Epic Choir",
        duration: "00:02:37",
        size: "9MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:33",
        size: "3MB",
      },
      {
        song: "The Final Battle",
        Performers: "Alan Silvestri Band",
        duration: "00:02:45",
        size: "4MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:09",
        size: "9MB",
      },
      {
        song: "The Siege",
        Performers: "James Horner & The Epic Choir",
        duration: "00:05:25",
        size: "10MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:15",
        size: "6MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "John Williams Philharmonic",
        duration: "00:04:37",
        size: "9MB",
      },
      {
        song: "The Last Stand",
        Performers: "John Williams Philharmonic",
        duration: "00:04:00",
        size: "5MB",
      },
      {
        song: "A New Dawn",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:26",
        size: "9MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "John Williams Philharmonic",
        duration: "00:04:19",
        size: "4MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:05:55",
        size: "6MB",
      },
      {
        song: "A New Dawn",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:03:22",
        size: "7MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:02:07",
        size: "10MB",
      },
    ],
  },
  {
    id: 3562,
    songs: [
      {
        song: "The Final Battle",
        Performers: "Illayaraja & The Symphony",
        duration: "00:06:45",
        size: "8MB",
      },
      {
        song: "The Siege",
        Performers: "John Williams Philharmonic",
        duration: "00:04:41",
        size: "6MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Yanni & The Fusion Band",
        duration: "00:04:29",
        size: "5MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:03:15",
        size: "3MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Max Richter Piano Quartet",
        duration: "00:04:11",
        size: "4MB",
      },
      {
        song: "Helen's Lament",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:06:50",
        size: "7MB",
      },
      {
        song: "The Last Stand",
        Performers: "Illayaraja & The Symphony",
        duration: "00:03:24",
        size: "4MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:08",
        size: "7MB",
      },
      {
        song: "The Last Stand",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:06:47",
        size: "9MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Yanni & The Fusion Band",
        duration: "00:04:52",
        size: "6MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Max Richter Piano Quartet",
        duration: "00:02:28",
        size: "9MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "John Williams Philharmonic",
        duration: "00:03:05",
        size: "4MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "AR Rahman & The Choir",
        duration: "00:03:28",
        size: "9MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "John Williams Philharmonic",
        duration: "00:04:29",
        size: "10MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:30",
        size: "8MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Yanni & The Fusion Band",
        duration: "00:04:08",
        size: "3MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:26",
        size: "5MB",
      },
      {
        song: "The Last Stand",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:06:35",
        size: "9MB",
      },
    ],
  },
  {
    id: 1149,
    songs: [
      {
        song: "Fate of the Warriors",
        Performers: "Alan Silvestri Band",
        duration: "00:03:32",
        size: "7MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:38",
        size: "9MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:40",
        size: "10MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:04:40",
        size: "4MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:58",
        size: "4MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "John Williams Philharmonic",
        duration: "00:05:06",
        size: "4MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:06:31",
        size: "4MB",
      },
      {
        song: "Epic Overture",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:04:33",
        size: "6MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Yanni & The Fusion Band",
        duration: "00:02:06",
        size: "5MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:01",
        size: "3MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:02:19",
        size: "8MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:05:47",
        size: "6MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:30",
        size: "7MB",
      },
      {
        song: "Epic Overture",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:05:16",
        size: "3MB",
      },
    ],
  },
  {
    id: 9389,
    songs: [
      {
        song: "The Fallen Kingdom",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:21",
        size: "7MB",
      },
    ],
  },
  {
    id: 7994,
    songs: [
      {
        song: "Beyond the Horizon",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:02:35",
        size: "8MB",
      },
    ],
  },
  {
    id: 7640,
    songs: [
      {
        song: "Fate of the Warriors",
        Performers: "Alan Silvestri Band",
        duration: "00:06:00",
        size: "9MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Alan Silvestri Band",
        duration: "00:03:13",
        size: "7MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:01",
        size: "8MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:03:57",
        size: "9MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "James Horner & The Epic Choir",
        duration: "00:06:54",
        size: "10MB",
      },
      {
        song: "Trojan War",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:05:43",
        size: "3MB",
      },
      {
        song: "A New Dawn",
        Performers: "Max Richter Piano Quartet",
        duration: "00:06:48",
        size: "3MB",
      },
      {
        song: "Battle of the Gods",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:02:50",
        size: "4MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Max Richter Piano Quartet",
        duration: "00:03:04",
        size: "10MB",
      },
      {
        song: "The Last Stand",
        Performers: "James Horner & The Epic Choir",
        duration: "00:06:23",
        size: "4MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "James Horner & The Epic Choir",
        duration: "00:05:06",
        size: "4MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:03:24",
        size: "8MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:04:12",
        size: "7MB",
      },
      {
        song: "Trojan War",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:03:43",
        size: "7MB",
      },
      {
        song: "The Final Battle",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:03:56",
        size: "10MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "John Williams Philharmonic",
        duration: "00:02:38",
        size: "4MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:04",
        size: "9MB",
      },
    ],
  },
  {
    id: 6763,
    songs: [
      {
        song: "The Siege",
        Performers: "Illayaraja & The Symphony",
        duration: "00:06:51",
        size: "5MB",
      },
      {
        song: "Helen's Lament",
        Performers: "AR Rahman & The Choir",
        duration: "00:04:26",
        size: "5MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:53",
        size: "4MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:06:43",
        size: "4MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:05:28",
        size: "3MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:05:37",
        size: "4MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:07",
        size: "3MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Max Richter Piano Quartet",
        duration: "00:04:20",
        size: "7MB",
      },
      {
        song: "The Siege",
        Performers: "John Williams Philharmonic",
        duration: "00:04:23",
        size: "4MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:36",
        size: "10MB",
      },
    ],
  },
  {
    id: 7195,
    songs: [
      {
        song: "The Final Battle",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:10",
        size: "9MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "James Horner & The Epic Choir",
        duration: "00:05:23",
        size: "7MB",
      },
      {
        song: "Valhalla Awaits",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:50",
        size: "6MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Illayaraja & The Symphony",
        duration: "00:05:30",
        size: "3MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:06:50",
        size: "4MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:43",
        size: "4MB",
      },
      {
        song: "Trojan War",
        Performers: "Alan Silvestri Band",
        duration: "00:03:44",
        size: "5MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "James Horner & The Epic Choir",
        duration: "00:06:38",
        size: "7MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:48",
        size: "3MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:03",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers: "Alan Silvestri Band",
        duration: "00:03:00",
        size: "9MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:29",
        size: "6MB",
      },
      {
        song: "The Final Battle",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:46",
        size: "7MB",
      },
      {
        song: "A Warrior Farewell",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:05:05",
        size: "6MB",
      },
      {
        song: "Legends Never Die",
        Performers: "AR Rahman & The Choir",
        duration: "00:05:41",
        size: "9MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:18",
        size: "10MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "James Horner & The Epic Choir",
        duration: "00:04:25",
        size: "8MB",
      },
      {
        song: "A New Dawn",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:02:11",
        size: "6MB",
      },
    ],
  },
  {
    id: 6437,
    songs: [
      {
        song: "Eternal Reign",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:03:10",
        size: "10MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Max Richter Piano Quartet",
        duration: "00:04:49",
        size: "5MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:04:52",
        size: "5MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:04:18",
        size: "3MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:02:22",
        size: "9MB",
      },
      {
        song: "A New Dawn",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:06:19",
        size: "10MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:07",
        size: "8MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Alan Silvestri Band",
        duration: "00:04:45",
        size: "5MB",
      },
      {
        song: "Helen's Lament",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:03:35",
        size: "3MB",
      },
      {
        song: "The Siege",
        Performers: "Yanni & The Fusion Band",
        duration: "00:02:19",
        size: "5MB",
      },
      {
        song: "The Last Stand",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:03:29",
        size: "8MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:05:33",
        size: "4MB",
      },
    ],
  },
  {
    id: 9741,
    songs: [
      {
        song: "Legends Never Die",
        Performers: "Yanni & The Fusion Band",
        duration: "00:05:33",
        size: "6MB",
      },
      {
        song: "The Siege",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:02:32",
        size: "5MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:04:31",
        size: "5MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:14",
        size: "10MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:05:26",
        size: "4MB",
      },
      {
        song: "Epic Overture",
        Performers: "James Horner & The Epic Choir",
        duration: "00:02:44",
        size: "7MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Alan Silvestri Band",
        duration: "00:06:56",
        size: "8MB",
      },
      {
        song: "Helen's Lament",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:04:06",
        size: "9MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:03:04",
        size: "5MB",
      },
      {
        song: "The Last Stand",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:03:14",
        size: "4MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "John Williams Philharmonic",
        duration: "00:03:46",
        size: "8MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:05:48",
        size: "8MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:03:32",
        size: "10MB",
      },
      {
        song: "The Siege",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:03:14",
        size: "5MB",
      },
      {
        song: "A New Dawn",
        Performers: "Alan Silvestri Band",
        duration: "00:02:33",
        size: "9MB",
      },
      {
        song: "Helen's Lament",
        Performers: "James Horner & The Epic Choir",
        duration: "00:04:17",
        size: "4MB",
      },
    ],
  },
  {
    id: 7516,
    songs: [
      {
        song: "Odysseus' Journey",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:02:28",
        size: "6MB",
      },
      {
        song: "The Final Battle",
        Performers: "AR Rahman & The Choir",
        duration: "00:04:24",
        size: "3MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:07",
        size: "6MB",
      },
      {
        song: "A New Dawn",
        Performers: "Alan Silvestri Band",
        duration: "00:02:39",
        size: "5MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Max Richter Piano Quartet",
        duration: "00:03:26",
        size: "7MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "AR Rahman & The Choir",
        duration: "00:04:45",
        size: "7MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:03:34",
        size: "6MB",
      },
      {
        song: "A New Dawn",
        Performers: "Alan Silvestri Band",
        duration: "00:03:38",
        size: "3MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "John Williams Philharmonic",
        duration: "00:02:21",
        size: "3MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:03:16",
        size: "10MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:28",
        size: "3MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:03:48",
        size: "4MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:14",
        size: "9MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Yanni & The Fusion Band",
        duration: "00:05:57",
        size: "10MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "James Horner & The Epic Choir",
        duration: "00:02:53",
        size: "6MB",
      },
    ],
  },
  {
    id: 9958,
    songs: [
      {
        song: "Beyond the Horizon",
        Performers: "Alan Silvestri Band",
        duration: "00:05:08",
        size: "4MB",
      },
      {
        song: "The Final Battle",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:22",
        size: "3MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:05:00",
        size: "8MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:04:34",
        size: "10MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:26",
        size: "4MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:06:32",
        size: "9MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Illayaraja & The Symphony",
        duration: "00:03:54",
        size: "5MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:06:52",
        size: "4MB",
      },
      {
        song: "Epic Overture",
        Performers: "Alan Silvestri Band",
        duration: "00:05:37",
        size: "9MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "AR Rahman & The Choir",
        duration: "00:05:09",
        size: "6MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:03:31",
        size: "6MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:03",
        size: "9MB",
      },
    ],
  },
  {
    id: 8079,
    songs: [
      {
        song: "The Wooden Horse",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:05:26",
        size: "7MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Yanni & The Fusion Band",
        duration: "00:06:13",
        size: "7MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:40",
        size: "4MB",
      },
      {
        song: "Valhalla Awaits",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:06:30",
        size: "4MB",
      },
      {
        song: "Epic Overture",
        Performers: "Yanni & The Fusion Band",
        duration: "00:06:54",
        size: "5MB",
      },
      {
        song: "A New Dawn",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:05:32",
        size: "5MB",
      },
    ],
  },
  {
    id: 9763,
    songs: [
      {
        song: "Beyond the Horizon",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:01",
        size: "10MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "John Williams Philharmonic",
        duration: "00:04:44",
        size: "4MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:08",
        size: "4MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:06:14",
        size: "6MB",
      },
      {
        song: "Epic Overture",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:03",
        size: "5MB",
      },
      {
        song: "The Wooden Horse",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:04:36",
        size: "9MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:18",
        size: "10MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:45",
        size: "10MB",
      },
      {
        song: "Trojan War",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:02:37",
        size: "5MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:34",
        size: "6MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Alan Silvestri Band",
        duration: "00:05:17",
        size: "3MB",
      },
      {
        song: "Epic Overture",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:21",
        size: "10MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:44",
        size: "10MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:25",
        size: "6MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:56",
        size: "3MB",
      },
      {
        song: "The Final Battle",
        Performers: "Max Richter Piano Quartet",
        duration: "00:03:26",
        size: "10MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Illayaraja & The Symphony",
        duration: "00:04:11",
        size: "3MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:41",
        size: "5MB",
      },
    ],
  },
  {
    id: 4806,
    songs: [
      {
        song: "Legends Never Die",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:06:46",
        size: "4MB",
      },
    ],
  },
  {
    id: 8903,
    songs: [
      {
        song: "Helen's Lament",
        Performers: "James Horner & The Epic Choir",
        duration: "00:04:46",
        size: "8MB",
      },
    ],
  },
  {
    id: 9109,
    songs: [
      {
        song: "The Last Stand",
        Performers: "Alan Silvestri Band",
        duration: "00:02:24",
        size: "8MB",
      },
    ],
  },
  {
    id: 5402,
    songs: [
      {
        song: "Rise of the Phoenix",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:05:00",
        size: "8MB",
      },
    ],
  },
  {
    id: 3656,
    songs: [
      {
        song: "The Siege",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:03:12",
        size: "7MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:02:54",
        size: "7MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Yanni & The Fusion Band",
        duration: "00:06:00",
        size: "8MB",
      },
      {
        song: "The Final Battle",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:40",
        size: "8MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Alan Silvestri Band",
        duration: "00:04:42",
        size: "8MB",
      },
      {
        song: "Trojan War",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:04:32",
        size: "5MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:06:54",
        size: "6MB",
      },
      {
        song: "A New Dawn",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:05:29",
        size: "3MB",
      },
    ],
  },
  {
    id: 8542,
    songs: [
      {
        song: "The Siege",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:02:26",
        size: "3MB",
      },
      {
        song: "The Horse and the Infant",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:06:06",
        size: "4MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Illayaraja & The Symphony",
        duration: "00:06:38",
        size: "6MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:03:52",
        size: "10MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:31",
        size: "6MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:04:54",
        size: "3MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:02:58",
        size: "8MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:29",
        size: "8MB",
      },
      {
        song: "The Final Battle",
        Performers: "Alan Silvestri Band",
        duration: "00:02:04",
        size: "6MB",
      },
      {
        song: "The Siege",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:02:08",
        size: "7MB",
      },
      {
        song: "The Last Stand",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:04:40",
        size: "3MB",
      },
      {
        song: "The Final Battle",
        Performers: "Illayaraja & The Symphony",
        duration: "00:06:41",
        size: "7MB",
      },
      {
        song: "Helen's Lament",
        Performers: "Yanni & The Fusion Band",
        duration: "00:04:59",
        size: "4MB",
      },
      {
        song: "The Siege",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:54",
        size: "6MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Alan Silvestri Band",
        duration: "00:06:22",
        size: "9MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Alan Silvestri Band",
        duration: "00:06:22",
        size: "4MB",
      },
    ],
  },
  {
    id: 5021,
    songs: [
      {
        song: "Storm of Destiny",
        Performers: "James Horner & The Epic Choir",
        duration: "00:03:07",
        size: "4MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:05:06",
        size: "8MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:53",
        size: "5MB",
      },
      {
        song: "Epic Overture",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:32",
        size: "10MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Alan Silvestri Band",
        duration: "00:02:15",
        size: "7MB",
      },
    ],
  },
  {
    id: 9200,
    songs: [
      {
        song: "Fate of the Warriors",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:34",
        size: "8MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:25",
        size: "7MB",
      },
      {
        song: "Epic Overture",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:52",
        size: "10MB",
      },
      {
        song: "The Last Stand",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:02:29",
        size: "8MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "James Horner & The Epic Choir",
        duration: "00:04:21",
        size: "6MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:57",
        size: "3MB",
      },
      {
        song: "Epic Overture",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:53",
        size: "10MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:03:58",
        size: "9MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:20",
        size: "4MB",
      },
      {
        song: "The Last Stand",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:05:06",
        size: "7MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Max Richter Piano Quartet",
        duration: "00:02:33",
        size: "6MB",
      },
    ],
  },
  {
    id: 3674,
    songs: [
      {
        song: "The Fallen Kingdom",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:04:28",
        size: "9MB",
      },
      {
        song: "The Final Battle",
        Performers: "John Williams Philharmonic",
        duration: "00:03:56",
        size: "4MB",
      },
      {
        song: "The Final Battle",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:36",
        size: "9MB",
      },
      {
        song: "A New Dawn",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:08",
        size: "5MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:02",
        size: "7MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:06:05",
        size: "8MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:46",
        size: "8MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:03:39",
        size: "5MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "James Horner & The Epic Choir",
        duration: "00:06:09",
        size: "4MB",
      },
      {
        song: "Eternal Reign",
        Performers: "James Horner & The Epic Choir",
        duration: "00:03:23",
        size: "9MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:06:31",
        size: "5MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Alan Silvestri Band",
        duration: "00:05:02",
        size: "4MB",
      },
      {
        song: "A New Dawn",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:05:06",
        size: "8MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:54",
        size: "5MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Alan Silvestri Band",
        duration: "00:04:40",
        size: "8MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "James Horner & The Epic Choir",
        duration: "00:02:38",
        size: "5MB",
      },
    ],
  },
  {
    id: 8403,
    songs: [
      {
        song: "The Horse and the Infant",
        Performers: "Max Richter Piano Quartet",
        duration: "00:04:29",
        size: "3MB",
      },
    ],
  },
  {
    id: 8196,
    songs: [
      {
        song: "The Forgotten Melody",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:23",
        size: "7MB",
      },
      {
        song: "Fate of the Warriors",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:05:48",
        size: "6MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:05:19",
        size: "7MB",
      },
      {
        song: "Trojan War",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:06",
        size: "6MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Illayaraja & The Symphony",
        duration: "00:03:35",
        size: "8MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:05:43",
        size: "8MB",
      },
      {
        song: "The Last Stand",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:17",
        size: "9MB",
      },
      {
        song: "Legends Never Die",
        Performers: "John Williams Philharmonic",
        duration: "00:06:47",
        size: "5MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:13",
        size: "4MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:03:39",
        size: "5MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "Alan Silvestri Band",
        duration: "00:02:12",
        size: "6MB",
      },
      {
        song: "The Final Battle",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:18",
        size: "7MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "Alan Silvestri Band",
        duration: "00:06:02",
        size: "8MB",
      },
      {
        song: "The Last Stand",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:05:08",
        size: "9MB",
      },
    ],
  },
  {
    id: 1419,
    songs: [
      {
        song: "Legends Never Die",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:05:44",
        size: "9MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:05:41",
        size: "8MB",
      },
      {
        song: "Eternal Reign",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:02:54",
        size: "4MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:02",
        size: "10MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "AR Rahman & The Choir",
        duration: "00:03:41",
        size: "5MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "James Horner & The Epic Choir",
        duration: "00:06:09",
        size: "3MB",
      },
      {
        song: "Epic Overture",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:03:16",
        size: "8MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "James Horner & The Epic Choir",
        duration: "00:02:42",
        size: "9MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:02:41",
        size: "10MB",
      },
    ],
  },
  {
    id: 7282,
    songs: [
      {
        song: "The Final Battle",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:06",
        size: "5MB",
      },
      {
        song: "Helen's Lament",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:05:42",
        size: "6MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:02:35",
        size: "8MB",
      },
      {
        song: "Trojan War",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:04:38",
        size: "9MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:02:32",
        size: "4MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:52",
        size: "10MB",
      },
    ],
  },
  {
    id: 7050,
    songs: [
      {
        song: "Epic Overture",
        Performers: "AR Rahman & The Choir",
        duration: "00:05:49",
        size: "8MB",
      },
      {
        song: "Spartan Anthem",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:04:31",
        size: "3MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:40",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:05:01",
        size: "7MB",
      },
      {
        song: "Helen's Lament",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:03:44",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers: "James Horner & The Epic Choir",
        duration: "00:03:03",
        size: "4MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Yanni & The Fusion Band",
        duration: "00:05:10",
        size: "7MB",
      },
      {
        song: "Achilles' Wrath",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:05:04",
        size: "5MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:58",
        size: "9MB",
      },
    ],
  },
  {
    id: 5655,
    songs: [
      {
        song: "The Siege",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:06:39",
        size: "9MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:52",
        size: "9MB",
      },
      {
        song: "The Last Stand",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:04:37",
        size: "4MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:07",
        size: "3MB",
      },
      {
        song: "Helen's Lament",
        Performers: "Illayaraja & The Symphony",
        duration: "00:04:30",
        size: "3MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Alan Silvestri Band",
        duration: "00:06:45",
        size: "5MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Illayaraja & The Symphony",
        duration: "00:03:09",
        size: "10MB",
      },
      {
        song: "A Warrior Farewell",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:06:09",
        size: "7MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:06:51",
        size: "5MB",
      },
      {
        song: "Trojan War",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:04:02",
        size: "8MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "John Williams Philharmonic",
        duration: "00:06:03",
        size: "10MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:03:31",
        size: "8MB",
      },
      {
        song: "Epic Overture",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:03:06",
        size: "7MB",
      },
    ],
  },
  {
    id: 5111,
    songs: [
      {
        song: "The Final Battle",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:03:41",
        size: "3MB",
      },
    ],
  },
  {
    id: 5597,
    songs: [
      {
        song: "Odysseus' Journey",
        Performers: "James Horner & The Epic Choir",
        duration: "00:03:36",
        size: "8MB",
      },
    ],
  },
  {
    id: 2841,
    songs: [
      {
        song: "The Fallen Kingdom",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:09",
        size: "8MB",
      },
      {
        song: "A New Dawn",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:06:29",
        size: "4MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:03:39",
        size: "8MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:47",
        size: "7MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:03:41",
        size: "9MB",
      },
    ],
  },
  {
    id: 3220,
    songs: [
      {
        song: "Fate of the Warriors",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:11",
        size: "6MB",
      },
    ],
  },
  {
    id: 5145,
    songs: [
      {
        song: "The Wooden Horse",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:05:11",
        size: "6MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Max Richter Piano Quartet",
        duration: "00:06:06",
        size: "6MB",
      },
      {
        song: "Helen's Lament",
        Performers: "AR Rahman & The Choir",
        duration: "00:05:33",
        size: "4MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "AR Rahman & The Choir",
        duration: "00:02:39",
        size: "6MB",
      },
      {
        song: "Legends Never Die",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:14",
        size: "5MB",
      },
      {
        song: "The Siege",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:03:25",
        size: "3MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Alan Silvestri Band",
        duration: "00:06:13",
        size: "5MB",
      },
    ],
  },
  {
    id: 7994,
    songs: [
      {
        song: "Eternal Reign",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:20",
        size: "10MB",
      },
      {
        song: "Trojan War",
        Performers: "Alan Silvestri Band",
        duration: "00:04:47",
        size: "3MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:02:22",
        size: "9MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Illayaraja & The Symphony",
        duration: "00:06:48",
        size: "4MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "Yanni & The Fusion Band",
        duration: "00:05:36",
        size: "4MB",
      },
      {
        song: "The Siege",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:05:57",
        size: "7MB",
      },
      {
        song: "Spartan Anthem",
        Performers: "Illayaraja & The Symphony",
        duration: "00:06:02",
        size: "7MB",
      },
      {
        song: "Trojan War",
        Performers: "James Horner & The Epic Choir",
        duration: "00:06:59",
        size: "3MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:03:42",
        size: "10MB",
      },
      {
        song: "A New Dawn",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:06:47",
        size: "6MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:04:19",
        size: "5MB",
      },
    ],
  },
  {
    id: 5347,
    songs: [
      {
        song: "The Horse and the Infant",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:03:42",
        size: "4MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:36",
        size: "6MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:03:45",
        size: "8MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:05:05",
        size: "6MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "Alan Silvestri Band",
        duration: "00:05:56",
        size: "5MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Illayaraja & The Symphony",
        duration: "00:04:44",
        size: "10MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:48",
        size: "7MB",
      },
      {
        song: "Valhalla Awaits",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:10",
        size: "6MB",
      },
      {
        song: "Fate of the Warriors",
        Performers: "Illayaraja & The Symphony",
        duration: "00:02:14",
        size: "6MB",
      },
      {
        song: "The Forgotten Melody",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:04:31",
        size: "7MB",
      },
      {
        song: "A New Dawn",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:04:28",
        size: "10MB",
      },
      {
        song: "The Final Battle",
        Performers: "AR Rahman & The Choir",
        duration: "00:04:53",
        size: "9MB",
      },
      {
        song: "Epic Overture",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:04:20",
        size: "10MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "John Williams Philharmonic",
        duration: "00:02:51",
        size: "10MB",
      },
      {
        song: "A New Dawn",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:47",
        size: "8MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:02:11",
        size: "6MB",
      },
      {
        song: "Achilles' Wrath",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:03:07",
        size: "3MB",
      },
    ],
  },
  {
    id: 1661,
    songs: [
      {
        song: "Rise of the Phoenix",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:06:37",
        size: "4MB",
      },
    ],
  },
  {
    id: 1897,
    songs: [
      {
        song: "Helen's Lament",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:06:54",
        size: "6MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:06:39",
        size: "10MB",
      },
      {
        song: "The Last Stand",
        Performers: "Yanni & The Fusion Band",
        duration: "00:06:09",
        size: "8MB",
      },
      {
        song: "The Siege",
        Performers: "Max Richter Piano Quartet",
        duration: "00:02:39",
        size: "7MB",
      },
      {
        song: "The Last Stand",
        Performers: "Yanni & The Fusion Band",
        duration: "00:05:10",
        size: "7MB",
      },
      {
        song: "Eternal Reign",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:02:54",
        size: "8MB",
      },
      {
        song: "Echoes of Olympus",
        Performers: "Alan Silvestri Band",
        duration: "00:02:33",
        size: "6MB",
      },
      {
        song: "The Horse and the Infant",
        Performers: "Howard Shore & The Orchestra",
        duration: "00:04:27",
        size: "10MB",
      },
      {
        song: "Odysseus' Journey",
        Performers: "AR Rahman & The Choir",
        duration: "00:04:57",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers: "Philip Glass Minimalist Ensemble",
        duration: "00:06:03",
        size: "5MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:05:05",
        size: "6MB",
      },
      {
        song: "Valhalla Awaits",
        Performers:
          "Jorge Rivera-Herrans, Luke Holt & Cast of EPIC: The Musical",
        duration: "00:05:10",
        size: "4MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:02:26",
        size: "4MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:03:06",
        size: "9MB",
      },
      {
        song: "Eternal Reign",
        Performers: "Two Steps From Hell Ensemble",
        duration: "00:05:55",
        size: "6MB",
      },
      {
        song: "The Siege",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:03:13",
        size: "9MB",
      },
      {
        song: "Valhalla Awaits",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:06:15",
        size: "6MB",
      },
      {
        song: "The Fallen Kingdom",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:02:43",
        size: "4MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:02:01",
        size: "6MB",
      },
      {
        song: "Gladiator Honor",
        Performers: "Hans Zimmer Orchestra",
        duration: "00:03:23",
        size: "9MB",
      },
    ],
  },
  {
    id: 5947,
    songs: [
      {
        song: "Trojan War",
        Performers: "Max Richter Piano Quartet",
        duration: "00:04:11",
        size: "7MB",
      },
    ],
  },
  {
    id: 9913,
    songs: [
      {
        song: "Eternal Reign",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:34",
        size: "5MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Danny Elfman & The Gothic Symphony",
        duration: "00:05:20",
        size: "8MB",
      },
      {
        song: "Beyond the Horizon",
        Performers: "AR Rahman & The Choir",
        duration: "00:04:14",
        size: "7MB",
      },
      {
        song: "Rise of the Phoenix",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:04:31",
        size: "4MB",
      },
      {
        song: "Storm of Destiny",
        Performers: "Yanni & The Fusion Band",
        duration: "00:05:49",
        size: "5MB",
      },
      {
        song: "Trojan War",
        Performers: "Illayaraja & The Symphony",
        duration: "00:03:04",
        size: "3MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Yanni & The Fusion Band",
        duration: "00:02:27",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers: "John Williams Philharmonic",
        duration: "00:03:08",
        size: "6MB",
      },
      {
        song: "Battle of the Gods",
        Performers: "Yanni & The Fusion Band",
        duration: "00:03:43",
        size: "5MB",
      },
      {
        song: "The Final Battle",
        Performers: "Alan Silvestri Band",
        duration: "00:05:13",
        size: "7MB",
      },
      {
        song: "The Wooden Horse",
        Performers: "AR Rahman & The Choir",
        duration: "00:06:23",
        size: "3MB",
      },
      {
        song: "Epic Overture",
        Performers: "Illayaraja & The Symphony",
        duration: "00:04:31",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers: "Ennio Morricone & The Cinematic Strings",
        duration: "00:03:23",
        size: "3MB",
      },
      {
        song: "Trojan War",
        Performers: "Max Richter Piano Quartet",
        duration: "00:05:45",
        size: "4MB",
      },
      {
        song: "Epic Overture",
        Performers: "Ludovico Einaudi Ensemble",
        duration: "00:05:24",
        size: "5MB",
      },
    ],
  },
];
module.exports = { collection, CollectionswithSongs };


